# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Server to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build, Push and release Docker Image to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_SERVER_APP_NAME }}
        dockerfile_directory: ./server
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"
        process_type: web
